#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

CONFIG="network_switcher"
NAME="network_switcher"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/network_switcher daemon
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_set_param user root
    procd_close_instance
}

stop_service() {
    /usr/bin/network_switcher stop
}

reload_service() {
    stop
    start
}
